name: 'GAIATAN SOLUTIONS  '
favicon: null
layout_spectrum: 0.50241
typography_spectrum: 0.9494266530964524
title: 'the highest quality, science-driven products and services for #OrganicLiving, #Permaculture, #MindTraining, #OnlineBusiness'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: GA-gaiatan-solutions-organics
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.9528812228236347
  lightness: 0.256666811183095
  saturation: 0.08289654366672039
  rhythmicContrast: 0.642735973931849
purpose: []
