name: 'GAIATAN SOLUTIONS  '
favicon: null
layout_spectrum: 0.50241
typography_spectrum: 0.9494266530964524
title: 'OrganicLiving | Permaculture Design | MindTraining | OnlineBusiness| Insvestments'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: GA-gaiatan-solutions- eco
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#040000'
    - '#3c7876'
    - '#f96232'
    - '#fee76f'
    - '#72d3a6'
  brandStrength: 0.5
  lightness: 0.256666811183095
  saturation: 0.08289654366672039
  rhythmicContrast: 0.642735973931849
purpose: []
