typography_spectrum: 0.74835
color:
  brandColors:
    - '#292929'
    - '#ffffff'
    - '#ffaf22'
    - '#d02828'
    - '#fefc17'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.50241
analytics:
  google: GA-gaiatan-solutions- eco
  facebook: null
  twitter: null
name: 'GAIATAN SOLUTIONS  '
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: 'Aligned Living | Permaculutre | Sacred Economy  | Yoga | '
description: >-
  "The place to be to connect with all good things and people to nourish your
  body and soul"
purpose: []
