name: 'GAIATAN SOLUTIONS  '
favicon: null
layout_spectrum: 0.50241
typography_spectrum: 0.74835
title: 'OrganicLiving | Permaculture Design | MindTraining | OnlineBusiness| Insvestments'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: GA-gaiatan-solutions- eco
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#292929'
    - '#ffffff'
    - '#ffaf22'
    - '#d02828'
    - '#fefc17'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
